# Generated by Django 3.0.4 on 2020-05-07 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20200227_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='numero_ss',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='nss_invalido', message='El numero de seguridad social no es valido', regex='^(\\d{2})(\\d{2})(\\d{2})\\d{5}$')], verbose_name='Número de Seguro Social'),
        ),
    ]
